services:
  # PHP
  resetter-bundle-php82:
    container_name: resetter-bundle-php82
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PHP_TAG: 8.2-fpm
    volumes:
      - .:/srv/www:delegated
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM

  resetter-bundle-php83:
    container_name: resetter-bundle-php83
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PHP_TAG: 8.3-fpm
    volumes:
      - .:/srv/www:delegated
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM

  resetter-bundle-php84:
    container_name: resetter-bundle-php84
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PHP_TAG: 8.4-fpm
    volumes:
      - .:/srv/www:delegated
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM
